[project]
main-file="spin/serial-frontend.spin2"
#main-file="spin/ads-test.spin2"
libraries=[
]

[propeller]
kind="P2"
serial-device="/dev/serial/by-id/usb-Parallax_Inc_Propeller_P2-EVAL_PLX4L28HW-if00-port0"
